/**
 * J Language Primitive Documentation
 * 
 * Auto-generated by scripts/scrape-j-docs.cjs
 * Source: https://code.jsoftware.com/wiki/NuVoc
 * Generated: 2026-01-27T18:16:33.142Z
 * 
 * Run `node scripts/scrape-j-docs.cjs` to update from upstream docs.
 * 
 * LICENSE ATTRIBUTION:
 * The documentation content in this file is derived from the J Wiki (NuVoc).
 * Source: https://code.jsoftware.com/wiki/NuVoc
 * License: Creative Commons Attribution-ShareAlike
 * See THIRD_PARTY_LICENSES.md for full license text.
 */

export const jDocsMeta = {
    "language": "J",
    "source": "https://code.jsoftware.com/wiki/NuVoc",
    "scrapedAt": "2026-01-27T18:16:33.142Z",
    "version": "1.0.0"
};

export const jGlyphDocs = {
    "=": {
        "glyph": "=",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/eq",
        "monad": {
            "name": "Self-Classify",
            "description": ""
        },
        "dyad": {
            "name": "Equal",
            "description": "The Boolean result of comparing x and y atom by atom."
        }
    },
    "<": {
        "glyph": "<",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lt",
        "monad": {
            "name": "Box",
            "description": ""
        },
        "dyad": {
            "name": "Less Than",
            "description": "Compares x and y atom-by-atom. See Equal (=) for the details."
        }
    },
    "<.": {
        "glyph": "<.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ltdot",
        "monad": {
            "name": "Floor",
            "description": "The floor of y i.e. the largest integer less than or equal to y"
        },
        "dyad": {
            "name": "Lesser Of (Min)",
            "description": "1. Test whether numbers are integers or not."
        }
    },
    "<:": {
        "glyph": "<:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ltco",
        "monad": {
            "name": "Decrement",
            "description": "Equivalent to y-1"
        },
        "dyad": {
            "name": "Less Or Equal",
            "description": "1. Simplify a phrase which decrements a given value"
        }
    },
    ">": {
        "glyph": ">",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gt",
        "monad": {
            "name": "Open",
            "description": "Opens (undoes the boxing) of a boxed element or array of boxed elements."
        },
        "dyad": {
            "name": "Greater Than",
            "description": "To remove boxing that is no longer needed to protect the contents."
        }
    },
    ">.": {
        "glyph": ">.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gtdot",
        "monad": {
            "name": "Ceiling",
            "description": "The ceiling of y i.e. the smallest integer greater than or equal to y"
        },
        "dyad": {
            "name": "Greater Of (Max)",
            "description": "1. Test whether numbers are integers or not."
        }
    },
    ">:": {
        "glyph": ">:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gtco",
        "monad": {
            "name": "Increment",
            "description": "Equivalent to y+1."
        },
        "dyad": {
            "name": "Greater Or Equal",
            "description": "1. Simplify a phrase which increments a given value"
        }
    },
    "+": {
        "glyph": "+",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plus",
        "monad": {
            "name": "Conjugate",
            "description": "The complex conjugate of the number y"
        },
        "dyad": {
            "name": "Plus",
            "description": "1. Test z is real not complex"
        }
    },
    "+.": {
        "glyph": "+.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plusdot",
        "monad": {
            "name": "Real/Imag",
            "description": "Decomposes complex numbers into real and imaginary parts"
        },
        "dyad": {
            "name": "GCD (Or)",
            "description": "Real/Imaginary video"
        }
    },
    "+:": {
        "glyph": "+:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plusco",
        "monad": {
            "name": "Double",
            "description": "Equivalent to 2 * y."
        },
        "dyad": {
            "name": "Not-Or",
            "description": "Can lead to neater tacit expressions"
        }
    },
    "*": {
        "glyph": "*",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/star",
        "monad": {
            "name": "Signum",
            "description": "The sign of the number y"
        },
        "dyad": {
            "name": "Times",
            "description": "Locate negative elements in an array for special treatment"
        }
    },
    "*.": {
        "glyph": "*.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/stardot",
        "monad": {
            "name": "Length/Angle",
            "description": "Converts x-y coordinates (given as a complex number) to r-theta coordinates (\"theta\" being in radians). The angle is in the range (-&#960;,&#960;]"
        },
        "dyad": {
            "name": "LCM (And)",
            "description": "To convert (x,y) to polar coordinates"
        }
    },
    "*:": {
        "glyph": "*:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/starco",
        "monad": {
            "name": "Square",
            "description": "Equivalent to y ^ 2, the square of numeric noun y."
        },
        "dyad": {
            "name": "Not-And",
            "description": "Can lead to neater tacit expressions"
        }
    },
    "-": {
        "glyph": "-",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minus",
        "monad": {
            "name": "Negate",
            "description": "Negates value of number y"
        },
        "dyad": {
            "name": "Minus",
            "description": "Rank 0 0 -- operates on individual atoms of x and y, producing a result of the same shape -- WHY IS THIS IMPORTANT?"
        }
    },
    "-.": {
        "glyph": "-.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minusdot",
        "monad": {
            "name": "Not",
            "description": "Equivalent to 1 - y ."
        },
        "dyad": {
            "name": "Less",
            "description": "Combinations using -. y that have exceptionally good performance include:"
        }
    },
    "-:": {
        "glyph": "-:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minusco",
        "monad": {
            "name": "Halve",
            "description": "Equivalent to y&#160;% 2 (y divided by 2)."
        },
        "dyad": {
            "name": "Match",
            "description": "Has advantages in tacit definitions over (expression)%2."
        }
    },
    "%": {
        "glyph": "%",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percent",
        "monad": {
            "name": "Reciprocal",
            "description": "Equivalent to 1&#160;% y, the reciprocal of the number y"
        },
        "dyad": {
            "name": "Divide",
            "description": "1. The reciprocals of positive and negative infinity are positive and negative zero. Positive and negative zero are equal in all comparisons and behave identically except when you divide by them:"
        }
    },
    "%.": {
        "glyph": "%.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percentdot",
        "monad": {
            "name": "Matrix Inverse",
            "description": "x&#160;%. y is (%. y) mux x where mux denotes matrix multiplication."
        },
        "dyad": {
            "name": "Matrix Divide",
            "description": "1. To reverse the effect of a linear transformation."
        }
    },
    "%:": {
        "glyph": "%:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percentco",
        "monad": {
            "name": "Square Root",
            "description": "The square root of y ."
        },
        "dyad": {
            "name": "Root",
            "description": "Can lead to neater tacit expressions than using (y^0.5)."
        }
    },
    "^": {
        "glyph": "^",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hat",
        "monad": {
            "name": "Exponential",
            "description": "ey, the y-th power of the mathematical constant: e ."
        },
        "dyad": {
            "name": "Power",
            "description": "Logarithm (^. y)"
        }
    },
    "^.": {
        "glyph": "^.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hatdot",
        "monad": {
            "name": "Natural Log",
            "description": "ln &#x2061; y {\\displaystyle \\ln y} or log e &#x2061; y {\\displaystyle \\log _{e}y} - the natural logarithm of y ."
        },
        "dyad": {
            "name": "Logarithm",
            "description": "Exponential (^ y)"
        }
    },
    "$": {
        "glyph": "$",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollar",
        "monad": {
            "name": "Shape Of",
            "description": ""
        },
        "dyad": {
            "name": "Shape",
            "description": "Creates an array whose shape depends on x and the shape of y. $ uses items of y; ($,) uses atoms of y;"
        }
    },
    "$.": {
        "glyph": "$.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollardot",
        "monad": {
            "name": "Sparse",
            "description": ""
        },
        "dyad": {
            "name": "Sparse",
            "description": "Gives a noun that can replace (numeric) y in working code, with only the non-zero atoms of $.y stored in memory. See the entry in the J Dictionary for details"
        }
    },
    "~.": {
        "glyph": "~.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tildedot",
        "monad": {
            "name": "Nub",
            "description": ""
        }
    },
    "~:": {
        "glyph": "~:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tildeco",
        "monad": {
            "name": "Nub Sieve",
            "description": ""
        },
        "dyad": {
            "name": "Not-Equal",
            "description": "The Boolean result of comparing two items, or lists of items, atom by atom."
        }
    },
    "|": {
        "glyph": "|",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bar",
        "monad": {
            "name": "Magnitude",
            "description": "The absolute value of numeric y. If y is complex, |y is the magnitude of y."
        },
        "dyad": {
            "name": "Residue",
            "description": "To separate out the absolute values and the signs of a list of numbers"
        }
    },
    "|.": {
        "glyph": "|.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bardot",
        "monad": {
            "name": "Reverse",
            "description": ""
        },
        "dyad": {
            "name": "Rotate",
            "description": "Rotates the items of y leftwards or upwards x positions. See below for Shift instead of Rotate."
        }
    },
    "|:": {
        "glyph": "|:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/barco",
        "monad": {
            "name": "Transpose",
            "description": ""
        },
        "dyad": {
            "name": "Rearrange Axes",
            "description": "Rearranges the axes of an array y."
        }
    },
    ",": {
        "glyph": ",",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/comma",
        "monad": {
            "name": "Ravel",
            "description": ""
        },
        "dyad": {
            "name": "Append",
            "description": "Produces a list containing all the atoms in y, in the order in which they appear in the display of y."
        }
    },
    ",.": {
        "glyph": ",.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/commadot",
        "monad": {
            "name": "Ravel Items",
            "description": ""
        },
        "dyad": {
            "name": "Stitch",
            "description": "Creates a table where each row of the table comes from an item of y."
        }
    },
    ",:": {
        "glyph": ",:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/commaco",
        "monad": {
            "name": "Itemize",
            "description": ""
        },
        "dyad": {
            "name": "Laminate",
            "description": "Creates an array whose rank is 1 more than the rank of y, and whose single item is y ."
        }
    },
    ";": {
        "glyph": ";",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semi",
        "monad": {
            "name": "Raze",
            "description": ""
        },
        "dyad": {
            "name": "Link",
            "description": "Removes one level of boxing from a noun. Cells of the contents of each box then become the items of the result."
        }
    },
    ";:": {
        "glyph": ";:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semico",
        "monad": {
            "name": "Words",
            "description": "Partitions a string into boxed words according to J's rules for word formation."
        },
        "dyad": {
            "name": "Sequential Machine",
            "description": "1. Partition an open list into boxed strings"
        }
    },
    "#": {
        "glyph": "#",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/number",
        "monad": {
            "name": "Tally",
            "description": ""
        },
        "dyad": {
            "name": "Copy",
            "description": "Creates a new array in which each integer in x controls how many times the corresponding item of y appears"
        }
    },
    "#.": {
        "glyph": "#.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/numberdot",
        "monad": {
            "name": "Base 2",
            "description": "The corresponding number of a binary numeral, given as a Boolean list"
        },
        "dyad": {
            "name": "Base",
            "description": "1. Binary to decimal conversion"
        }
    },
    "#:": {
        "glyph": "#:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/numberco",
        "monad": {
            "name": "Antibase 2",
            "description": ""
        },
        "dyad": {
            "name": "Antibase",
            "description": "Generalizes the action of (#: y) to other bases than 2 (including mixed bases)"
        }
    },
    "!": {
        "glyph": "!",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bang",
        "monad": {
            "name": "Factorial",
            "description": "The Factorial of y."
        },
        "dyad": {
            "name": "Out Of (Binomial)",
            "description": "Rank 0 0 -- operates on individual atoms of x and y, producing a result of the same shape -- WHY IS THIS IMPORTANT?"
        }
    },
    "[": {
        "glyph": "[",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelf",
        "monad": {
            "name": "Same",
            "description": ""
        },
        "dyad": {
            "name": "Left",
            "description": "Returns noun y unchanged: [y is equivalent to y."
        }
    },
    "]": {
        "glyph": "]",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarert",
        "monad": {
            "name": "Same",
            "description": ""
        },
        "dyad": {
            "name": "Right",
            "description": "Returns noun y unchanged, i.e. (]y) is equivalent to y."
        }
    },
    "{": {
        "glyph": "{",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylf",
        "monad": {
            "name": "Catalogue",
            "description": "Combines items from the atoms inside a boxed list to form a catalogue."
        },
        "dyad": {
            "name": "From",
            "description": "Form the Cartesian Product of two lists, x and y"
        }
    },
    "{.": {
        "glyph": "{.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfdot",
        "monad": {
            "name": "Head",
            "description": ""
        },
        "dyad": {
            "name": "Take",
            "description": "The leading x items of y."
        }
    },
    "{:": {
        "glyph": "{:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfco",
        "monad": {
            "name": "Tail",
            "description": ""
        }
    },
    "{::": {
        "glyph": "{::",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfcoco",
        "monad": {
            "name": "Map",
            "description": ""
        },
        "dyad": {
            "name": "Fetch",
            "description": "A list of the contents of selected boxes in a boxed noun: y"
        }
    },
    "}": {
        "glyph": "}",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrt",
        "monad": {
            "name": "Item Amend",
            "description": ""
        },
        "dyad": {
            "name": "Amend",
            "description": "Create an array having the shape of an item of y that's a composite of the items of y."
        }
    },
    "}.": {
        "glyph": "}.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrtdot",
        "monad": {
            "name": "Behead",
            "description": ""
        },
        "dyad": {
            "name": "Drop",
            "description": "Drop the leading x items of y"
        }
    },
    "}:": {
        "glyph": "}:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrtco",
        "monad": {
            "name": "Curtail",
            "description": ""
        }
    },
    "?": {
        "glyph": "?",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/query",
        "monad": {
            "name": "Roll",
            "description": "Generates a random number uniformly distributed in a range determined by integer y."
        },
        "dyad": {
            "name": "Deal",
            "description": "1. Make a random boolean matrix"
        }
    },
    "?.": {
        "glyph": "?.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/querydot",
        "monad": {
            "name": "Roll (fixed seed)",
            "description": ""
        },
        "dyad": {
            "name": "Deal (fixed seed)",
            "description": "Behaves like Roll/Deal (?) &#8212; except that the random-number generator (RNG) is reset each time ?. is executed."
        }
    },
    "i.": {
        "glyph": "i.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/idot",
        "monad": {
            "name": "Integers",
            "description": "Returns an ascending (or descending) sequence of integers, wrapped to the shape specified by (|y)."
        },
        "dyad": {
            "name": "Index Of",
            "description": "0. A video has been made showing common uses of the Integers monadic verb"
        }
    },
    "i:": {
        "glyph": "i:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ico",
        "monad": {
            "name": "Steps",
            "description": "Like Integers (i.), except that the sequence ranges from (-y) thru (+y)."
        },
        "dyad": {
            "name": "Index Of Last",
            "description": "1. i: y operates on each atom of y independently, and produces a list for each one."
        }
    },
    "I.": {
        "glyph": "I.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/icapdot",
        "monad": {
            "name": "Indices",
            "description": "The indexes of every 1 in the Boolean list y"
        },
        "dyad": {
            "name": "Interval Index",
            "description": "1. Convert a Boolean mask to the list of indexes where the mask is 1"
        }
    },
    "j.": {
        "glyph": "j.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/jdot",
        "monad": {
            "name": "Imaginary",
            "description": "Multiplies y by 0j1, which represents the imaginary unit i ."
        },
        "dyad": {
            "name": "Complex",
            "description": "Rank 0 0 -- operates on individual atoms of x and y, producing a result of the same shape -- WHY IS THIS IMPORTANT?"
        }
    },
    "o.": {
        "glyph": "o.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/odot",
        "monad": {
            "name": "Pi Times",
            "description": "Returns (&#960; times y) given any number y ."
        },
        "dyad": {
            "name": "Circle Function",
            "description": "1. Represent, in J, common physics expressions involving &#960;"
        }
    },
    "p.": {
        "glyph": "p.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/pdot",
        "monad": {
            "name": "Roots",
            "description": "Converts the polynomial y between coefficient and multiplier-and-roots form."
        },
        "dyad": {
            "name": "Polynomial",
            "description": "1. Solve a polynomial equation whose right side is 0 (the solutions are the roots)."
        }
    },
    "p:": {
        "glyph": "p:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/pco",
        "monad": {
            "name": "Primes",
            "description": "The y-th prime (starting with 2 as the 0-th prime)."
        }
    },
    "q:": {
        "glyph": "q:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/qco",
        "monad": {
            "name": "Prime Factors",
            "description": ""
        },
        "dyad": {
            "name": "Prime Exponents",
            "description": "Selected primes and their exponents in the factorization of y."
        }
    },
    "r.": {
        "glyph": "r.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/rdot",
        "monad": {
            "name": "Angle",
            "description": "The angle y (in radians), expressed as a unit vector in the complex plane"
        },
        "dyad": {
            "name": "Polar",
            "description": "1. Work with 2-D coordinate geometry."
        }
    },
    "x:": {
        "glyph": "x:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/xco",
        "monad": {
            "name": "Extended Precision",
            "description": ""
        }
    },
    "A.": {
        "glyph": "A.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/acapdot",
        "monad": {
            "name": "Anagram Index",
            "description": "A. y converts the permutation y into its permutation number (also called its anagram index)."
        },
        "dyad": {
            "name": "Anagram",
            "description": "1. Work conveniently with permutations, using the permutation number instead of the permutation itself."
        }
    },
    "C.": {
        "glyph": "C.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ccapdot",
        "monad": {
            "name": "Cycle-Direct",
            "description": "Converts the permutation y between direct and cycle representations."
        },
        "dyad": {
            "name": "Permute",
            "description": "1. Find the cycle form of a permutation, as above. In standard math notation the cycles are represented in parentheses, as"
        }
    },
    "e.": {
        "glyph": "e.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/edot",
        "monad": {
            "name": "Raze In",
            "description": ""
        },
        "dyad": {
            "name": "Member (In)",
            "description": "Returns a Boolean table comparing each box of y (a list of boxed atoms) against each atom in ;y (the Raze of y)."
        }
    },
    "E.": {
        "glyph": "E.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ecapdot",
        "dyad": {
            "name": "Find Matches",
            "description": "Create a Boolean array indicating starting points in y of subarrays equal to x."
        }
    },
    "L.": {
        "glyph": "L.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lcapdot",
        "monad": {
            "name": "Level Of",
            "description": ""
        }
    },
    "s:": {
        "glyph": "s:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/sco",
        "monad": {
            "name": "Symbol",
            "description": ""
        },
        "dyad": {
            "name": "Symbol",
            "description": "A symbol is an atom of a special type that stands for a list of characters. A symbol is an alternative to a boxed string."
        }
    },
    "u:": {
        "glyph": "u:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/uco",
        "monad": {
            "name": "Unicode",
            "description": ""
        },
        "dyad": {
            "name": "Unicode",
            "description": "The unicode character corresponding to y."
        }
    },
    "~": {
        "glyph": "~",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tilde",
        "monad": {
            "name": "Reflex",
            "description": ""
        },
        "dyad": {
            "name": "Passive",
            "description": "(u~ y) is the same as (y u y)"
        }
    },
    "/": {
        "glyph": "/",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slash",
        "monad": {
            "name": "Insert",
            "description": ""
        },
        "dyad": {
            "name": "Table",
            "description": "Inserts dyad u between the items of y"
        }
    },
    "/.": {
        "glyph": "/.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slashdot",
        "monad": {
            "name": "Oblique",
            "description": ""
        },
        "dyad": {
            "name": "Key",
            "description": "(u/.y) applies verb u to the oblique diagonals of table y"
        }
    },
    "/:": {
        "glyph": "/:",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slashco",
        "monad": {
            "name": "Grade Up",
            "description": ""
        },
        "dyad": {
            "name": "Sort Up",
            "description": "The permutation that sorts the items of y into ascending (/:) or descending (\\:) order (numerical or lexicographical)"
        }
    },
    "\\": {
        "glyph": "\\",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslash",
        "monad": {
            "name": "Prefix",
            "description": ""
        },
        "dyad": {
            "name": "Infix",
            "description": "(x u\\y) applies verb u to successive parts of list y (called infixes)."
        }
    },
    "\\.": {
        "glyph": "\\.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslashdot",
        "monad": {
            "name": "Suffix",
            "description": ""
        },
        "dyad": {
            "name": "Outfix",
            "description": "(x u\\. y) applies verb u to successive outfixes of y. Each outfix is y with an infix removed. The infixes depend on x, as described in Infix (\\)."
        }
    },
    "\\:": {
        "glyph": "\\:",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslashco",
        "monad": {
            "name": "Grade Down",
            "description": ""
        },
        "dyad": {
            "name": "Sort Down",
            "description": "The permutation that sorts list y into descending order (numerical or lexicographical)"
        }
    },
    "b.": {
        "glyph": "b.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bdot",
        "monad": {
            "name": "Boolean/Bitwise",
            "description": ""
        }
    },
    "f.": {
        "glyph": "f.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fdot",
        "monad": {
            "name": "Fix",
            "description": ""
        }
    },
    "M.": {
        "glyph": "M.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/mcapdot",
        "monad": {
            "name": "Memo",
            "description": ""
        }
    },
    "t.": {
        "glyph": "t.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tdot",
        "monad": {
            "name": "Taylor Coeff",
            "description": ""
        }
    },
    "^:": {
        "glyph": "^:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hatco",
        "monad": {
            "name": "Power (of verb)",
            "description": ""
        }
    },
    ".": {
        "glyph": ".",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dot",
        "monad": {
            "name": "Determinant",
            "description": "-/ . * y is the determinant of square matrix y ."
        },
        "dyad": {
            "name": "Dot Product",
            "description": "1. The space before . is required."
        }
    },
    ":": {
        "glyph": ":",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/cor",
        "monad": {
            "name": "Explicit",
            "description": ""
        },
        "dyad": {
            "name": "Explicit",
            "description": "Defines all types of entities."
        }
    },
    ":.": {
        "glyph": ":.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/codot",
        "monad": {
            "name": "Obverse",
            "description": ""
        }
    },
    "::": {
        "glyph": "::",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/coco",
        "monad": {
            "name": "Adverse",
            "description": ""
        }
    },
    ";.": {
        "glyph": ";.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semidot",
        "monad": {
            "name": "Cut",
            "description": ""
        },
        "dyad": {
            "name": "Cut",
            "description": "A collection of 3 adverbs, collectively known as Cut, with different syntax and semantics."
        }
    },
    "!.": {
        "glyph": "!.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bangdot",
        "monad": {
            "name": "Fit",
            "description": ""
        }
    },
    "!:": {
        "glyph": "!:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bangco",
        "monad": {
            "name": "Foreign",
            "description": ""
        }
    },
    "\"": {
        "glyph": "\"",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quote",
        "monad": {
            "name": "Rank",
            "description": ""
        }
    },
    "\".": {
        "glyph": "\".",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quotedot",
        "monad": {
            "name": "Do",
            "description": "Executes the sentence y, returning the result of the sentence as the result of \". y. y is a list of characters."
        },
        "dyad": {
            "name": "Numbers",
            "description": "1. Convert a number in literal form to a numeric type"
        }
    },
    "\":": {
        "glyph": "\":",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quoteco",
        "monad": {
            "name": "Default Format",
            "description": ""
        },
        "dyad": {
            "name": "Format",
            "description": "Converts y to a byte array formatted according to the specification x"
        }
    },
    "`": {
        "glyph": "`",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/grave",
        "monad": {
            "name": "Tie (Gerund)",
            "description": ""
        }
    },
    "`:": {
        "glyph": "`:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/graveco",
        "monad": {
            "name": "Evoke Gerund",
            "description": ""
        }
    },
    "@": {
        "glyph": "@",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/at",
        "monad": {
            "name": "Atop",
            "description": ""
        },
        "dyad": {
            "name": "Atop",
            "description": "u@v is equivalent to (u@:v)\"v. That is,"
        }
    },
    "@.": {
        "glyph": "@.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/atdot",
        "monad": {
            "name": "Agenda",
            "description": ""
        }
    },
    "@:": {
        "glyph": "@:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/atco",
        "monad": {
            "name": "At",
            "description": ""
        },
        "dyad": {
            "name": "At",
            "description": "Forms the composition of two verbs u and v ."
        }
    },
    "&": {
        "glyph": "&",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampm",
        "monad": {
            "name": "Bond",
            "description": ""
        },
        "dyad": {
            "name": "Compose",
            "description": "1. Weld a noun to a verb, creating a unit that bypasses processing by other modifiers. To prefix 'Mr. ' to each boxed string:"
        }
    },
    "&.": {
        "glyph": "&.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampdot",
        "monad": {
            "name": "Under (Dual)",
            "description": ""
        }
    },
    "&.:": {
        "glyph": "&.:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampdotco",
        "monad": {
            "name": "Under",
            "description": ""
        }
    },
    "&:": {
        "glyph": "&:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampco",
        "monad": {
            "name": "Appose",
            "description": ""
        }
    },
    "d.": {
        "glyph": "d.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ddot",
        "monad": {
            "name": "Derivative",
            "description": "The ordinary n-th derivative of [the mathematical function implemented by] verb u."
        }
    },
    "D.": {
        "glyph": "D.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dcapdot",
        "monad": {
            "name": "Derivative",
            "description": ""
        }
    },
    "D:": {
        "glyph": "D:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dcapco",
        "monad": {
            "name": "Secant Slope",
            "description": ""
        }
    },
    "F.": {
        "glyph": "F.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": ""
        }
    },
    "H.": {
        "glyph": "H.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hcapdot",
        "monad": {
            "name": "Hypergeometric",
            "description": ""
        }
    },
    "L:": {
        "glyph": "L:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lcapco",
        "monad": {
            "name": "Level At",
            "description": ""
        }
    },
    "S:": {
        "glyph": "S:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/scapco",
        "monad": {
            "name": "Spread",
            "description": ""
        }
    },
    "T.": {
        "glyph": "T.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tcapdot",
        "monad": {
            "name": "Taylor",
            "description": ""
        }
    },
    "$:": {
        "glyph": "$:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollarco",
        "monad": {
            "name": "Self-Reference",
            "description": ""
        },
        "dyad": {
            "name": "Self-Reference",
            "description": "Rank Infinity -- operates on [x and] y as a whole -- WHY IS THIS IMPORTANT?"
        }
    },
    "[.": {
        "glyph": "[.",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelfdot",
        "monad": {
            "name": "Lev",
            "description": ""
        }
    },
    "[:": {
        "glyph": "[:",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelfco",
        "monad": {
            "name": "Cap",
            "description": ""
        }
    },
    "].": {
        "glyph": "].",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarertdot",
        "monad": {
            "name": "Dex",
            "description": ""
        }
    },
    "]:": {
        "glyph": "]:",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarertco",
        "monad": {
            "name": "Ident",
            "description": ""
        }
    },
    "_": {
        "glyph": "_",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/under",
        "monad": {
            "name": "Negative Sign/Infinity",
            "description": ""
        }
    },
    "_.": {
        "glyph": "_.",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/underdot",
        "monad": {
            "name": "Indeterminate",
            "description": ""
        }
    },
    "a.": {
        "glyph": "a.",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/adot",
        "monad": {
            "name": "Alphabet",
            "description": ""
        }
    },
    "a:": {
        "glyph": "a:",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/aco",
        "monad": {
            "name": "Ace (Boxed Empty)",
            "description": ""
        }
    }
};

/**
 * Get hover content for a J primitive
 * @param {string} glyph - The glyph to look up
 * @returns {object|null} - The documentation object or null if not found
 */
export function getJHoverContent(glyph) {
    return jGlyphDocs[glyph] || null;
}
